export const DONORS = [
  { tradename: "GreenFields", stand: 101, market: 1, owner: "Juan Pérez" },
  { tradename: "FreshBloom", stand: 205, market: 3, owner: "María García" },
  {
    tradename: "Nature'sHarvest",
    stand: 303,
    market: 5,
    owner: "Luis Rodríguez",
  },
  { tradename: "OrganicGrove", stand: 415, market: 7, owner: "Ana Martínez" },
  { tradename: "FarmersPick", stand: 520, market: 10, owner: "Carlos Sánchez" },
  { tradename: "VeggieVitality", stand: 615, market: 2, owner: "Laura Gómez" },
  {
    tradename: "TasteBudsProduce",
    stand: 720,
    market: 4,
    owner: "David López",
  },
  { tradename: "HarvestHub", stand: 805, market: 6, owner: "Sofía Hernández" },
  { tradename: "FreshFusion", stand: 903, market: 8, owner: "Diego González" },
  { tradename: "UrbanGreens", stand: 1010, market: 9, owner: "Patricia Pérez" },
  { tradename: "MarketGrove", stand: 111, market: 1, owner: "Manuel Soto" },
  { tradename: "LeafyLife", stand: 122, market: 2, owner: "Elena Vargas" },
  {
    tradename: "NaturalHarvesters",
    stand: 133,
    market: 3,
    owner: "Pedro Torres",
  },
  { tradename: "BountyBarn", stand: 144, market: 4, owner: "Marta Ruiz" },
  {
    tradename: "GreenGardeners",
    stand: 155,
    market: 5,
    owner: "Jorge Fernández",
  },
  { tradename: "HarvestHaven", stand: 166, market: 6, owner: "Carmen Díaz" },
  { tradename: "FreshLand", stand: 177, market: 7, owner: "Ricardo Castro" },
  { tradename: "VeggieValley", stand: 188, market: 8, owner: "Isabel Flores" },
  { tradename: "PureProduce", stand: 199, market: 9, owner: "Gabriel Ramírez" },
  { tradename: "GreenGrocer", stand: 200, market: 10, owner: "Silvia Reyes" },
];
